---
title: "Book Club Details"
author: "Jenine Harris"
date: "October 24, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Book Club

Activities: 

(1) Read The Lady Tasting Tea by Salsburg (there are several copies on reserve in the Brown School library), paying attention to the topic you chose. If you cannot remember which topic you chose, see the course announcement from 10/24 in Blackboard. Here are the topics: 
    + Topic 1: The contributions and controversies of RA Fisher
    + Topic 2: Probability and Confidence Intervals (development of, relationship between, etc) 
    + Topic 3: The role of women in the development of statistics
    + Topic 4: Goodness of fit
    + Topic 5: Where the field may be headed next 

(2) Work with your book club group (the groups are posted as an announcement in Blackboard) to develop an activity or discussion related to your topic. This can take *any format* as long as the format encourages participation by the rest of the class (not a presentation). You should plan to lead the class for 20-30 minutes total. In the past, groups have:
    + Developed a set of questions to lead the class in a discussion (be sure to think about how to proceed if the class is very quiet!) 
    + Developed a Jeopardy, Who wants to be a millionaire, or other game show type game and divided the class into teams to compete to answer questions 
    + Divided the class into groups and had each group come up with the answer to a question and present their answer in some way 
    + Showed new R command(s) or package(s) and walked the class through how to use  
    + Demonstrated some statistical concept or formula and walked the class through how to use it 
    + Developed a mystery related to the topic with clues the class had to solve 
    + Developed a matching game where ideas or names are written on the board and individual students are each given a notecard with a fact to tape next to its matching idea or name 
    + Tested one of the ideas in the book with a brief in-class study  

(3) You will be reviewing your teammates and their contributions to your book club group, so be aware that this is part of the score. Your participation in book club also includes participating in whatever activities the other groups come up with, so *reading the book* is important! 

If you need copies or other materials for your activity, please email me ahead of time.  


